language: ruby
cache:
  bundler: true
rvm: 2.3.1
sudo: false
before_script:
  - bin/rake db:migrate
  - bin/setup

script:
  - bin/rake test
deploy:
  provider: heroku
  app: <%= ENV["DEPLOY_APP"] %>
  api_key:
    secure: <%= ENV["DEPLOY_KEY"] %>
