default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pick_another_dev

test:
  <<: *default
  database: pick_another_test

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
