default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pick_another_dev
  adapter: <%= ENV["DB_ADAPTER"] || "sqlite3" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

test:
  <<: *default
  database: pick_another_test

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
