default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: pick_another_dev
  # adapter: <%= ENV["DB_ADAPTER"] || "sqlite3" %>
  # host: <%= ENV["DB_HOST"] || "localhost" %>

test:
  <<: *default
  database: pick_another_test

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
